trigger: 
- master

pool:
    vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndTest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '>=6.10.0'
      displayName: 'Instalacija Node.js packeta na Ubuntu mašinu'

    - script: npm install
      displayName: 'Instaliranje dependencija'
    
    - script: npm test
      displayName: 'Pokretanje testova'  # This assumes you meant to run tests with `npm test`
    - script: cd MainSite
      displayName: 'Getting to MainSite folder'
    - script: npm run build
      displayName: 'Building MainSite'
