trigger: 
- master

pool:
    vmImage: 'ubuntu-latest'
jobs:
  - job: BuildAndTest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec:  '>=6.10.0'
      displayName: 'Instalacija Node.js packeta na ubunutu mašinu'
    - script: npm install
      displayName: 'instaliranje dependencia'
    - script: npm install
      displayName: 'Run tests'
    - script: npm run build
      displayName: 'Building project'
